version: "2"
services:
  app:
    image: busybox
    container_name: proxify_app
    depends_on:
      - "nginx"

  data:
    image: busybox
    container_name: proxify_data
    volumes:
      - .:/var/www

  nginx:
    image: webcodium/nginx:laravel
    container_name: proxify_nginx
    volumes_from:
      - data
    ports:
      - "80:80"
      - "443:443"
    environment:
      NGINX_HOST: proxify.local
      NGINX_HTTP_PORT: 80
      NGINX_HTTPS_PORT: 443
      NGINX_CLIENT_MAX_BODY_SIZE: 10m
      NGINX_VHOST_ROOT_DIRECTORY: /var/www/public
      FASTCGI_URL: php
    depends_on:
      - "php"

  php:
    image: artiden/php:7.2
    container_name: proxify_php
    volumes_from:
      - data
    depends_on:
      - "db"
    working_dir: /var/www
    environment:
      DB_DRIVER: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: proxify
      DB_USER: proxify
      DB_PASSWORD: proxify
      APP_KEY: base64:WfKnUNRUL0a76Lbqc4eI0vx565F4JgfPfpHs4Z3KrRk=
    command: >
            /bin/sh -c "envsubst < /var/www/.env.example > /var/www/.env &&
            rm -f /etc/php/7.2/mods-available/opcache.ini 
            && /usr/sbin/php-fpm7.2 -F -R"

  db:
    image: mysql:5.7.19
    container_name: proxify_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: proxify
      MYSQL_PASSWORD: proxify
      MYSQL_DATABASE: proxify
